# This configuration don't need any fancy font and is intended to be showed in any tty.
# The resulting information is focused on git.
# Requires v0.56.0^.

add_newline = false

format = """
[┌→](bold green)$status$cmd_duration$username$hostname$directory$git_branch$git_commit$git_state\
$git_metrics$git_status$package$time
[└─](bold green) ø """

[cmd_duration]
format = '[$duration](bold yellow) '
min_time = 2_000

[directory]
format = '[$path]($style) '
read_only_style = 'bold red'
style = 'bold'
truncate_to_repo = false
truncation_length = 69
truncation_symbol = '…/'

[git_branch]
format = '\[[git]($style)[⌂](purple)[$branch]($style)\] '
style = 'bold'

[git_commit]
commit_hash_length = 8
format = '[$hash](bold) '

[git_metrics]
disabled = false
format = '([+$added](green) [-$deleted](red) )'

[git_state]
format = '[$state](bold) '

[git_status]
ahead = '[${count}↑](green) '
behind = '[${count}↓](red) '
conflicted = '[↔](red) '
deleted = '[${count}×](red) '
diverged = '[↕](red)[${ahead_count}↑](green)[${behind_count}↓](red)'
format = '$all_status$ahead_behind'
modified = '[${count}!](red) '
renamed = '[${count}»](green) '
staged = '[${count}√](green) '
stashed = '[${count}\$](bold yellow) '
untracked = '[${count}?](red) '

[hostname]
disabled = false
format = '$hostname '
ssh_only = false

[package]
format = '\[[$version](bold)\] '

[status]
disabled = false
symbol = ''

[time]
time_format = '%T'
format = '[$time](white) '
disabled = false

[username]
format = '[$user]($style)@'
show_always = true
style_root = 'bold red'
style_user = 'yellow'
